language: php

php:
  - '5.6'
  - '7.1'

services:
  - mysql

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - mysql -e 'create database laravel_migrate_check;' -uroot

notifications:
  email: false
